---
grails:
    profile: rest-api
    codegen:
        defaultPackage: wts.server
    spring:
        transactionManagement:
            proxies: false
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false

# Spring Actuator Endpoints are Disabled by Default
endpoints:
    enabled: false
    jmx:
        enabled: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            json:
              - application/json
              - text/json   
            hal:
              - application/hal+json
              - application/hal+xml  
            xml:
              - text/xml
              - application/xml                                 
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            js: text/javascript
            rss: application/rss+xml
            text: text/plain
            all: '*/*'            
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    plugin:
        springsecurity:
#            digest:
#                useCleartextPasswords: false
#                useDigestAuth: true
            userLookup:
                userDomainClassName: 'com.infiniteintelligence.wts.domain.security.User'
                authorityJoinClassName: 'com.infiniteintelligence.wts.domain.security.UserRole'
            authority:
                className: 'com.infiniteintelligence.wts.domain.security.Role'
            filterChain:
                chainMap:
                    - pattern: '/api/**'
                      filters: 'JOINED_FILTERS,-anonymousAuthenticationFilter,-exceptionTranslationFilter,-authenticationProcessingFilter,-securityContextPersistenceFilter,-rememberMeAuthenticationFilter'
                    - pattern: '/**'
                      filters: 'JOINED_FILTERS,-restTokenValidationFilter,-restExceptionTranslationFilter'

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: oracle.jdbc.OracleDriver
    url: 'jdbc:oracle:thin:@localhost:1521:xe'
    username: 'WTS'
    password: 'WTS'

environments:
    development:
    test:
    production: